name: grand-theft-auto
targets:
  grand-theft-auto:
    platform: iOS
    type: application
    info:
      path: Info.plist
      proprties:
        version: 1.0
    sources: [App.swift]
    settings:
      DEVELOPMENT_TEAM: B3G57IU33I
      PRODUCT_BUNDLE_IDENTIFIER: com.example.app
