import { Inter } from 'next/font/google'
import type { Metadata } from 'next'

import './index.css'

export const metadata: Metadata = {
	title: 'Create Next App', description: 'Generated by create next application.'
}

type Props = Readonly<
	{
		children: React.ReactNode
	}
>

export default function RootLayout({ children }: Props) {
	return (
		<html lang='ru'>
			<body className={inter.className}>
				{children}
			</body>
		</html>
	)
}

const inter = Inter({
	subsets: ['latin']
})
