name: Build an iOS app
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew install xcodegen
      - run: xcodegen generate
      - run: ls -la grand-theft-auto.xcodeproj
      - uses: actions/upload-artifact@v4
        with:
          path: .
