name: Build an iOS app
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew install xcodegen
      - run: xcodegen generate
      - run: ls -la grand-theft-auto.xcodeproj
      - run: git add .;
      - run: git commit -m "create xcode files"
      - run: git push -f
