name: CMake
on:
  workflow_dispatch:

jobs:
  print:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: cmake --help
      - run: git clone https://github.com/keith2018/SoftGLRender.git
      - run: cd SoftGLRender
      - run: mkdir Xcode; cd Xcode
      - run: cmake -G Xcode ..
      - run: ls -la
