name: Does working-directory create a folder?
run-name: ${{ github.actor }} ran this workflow

on:
  workflow_dispatch:

jobs:
  mkdir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir i-want-to-be-in-created-folder
        working-directory: created-folder
      - uses: actions/upload-artifact@v3.1.3
