name: GitHub Pages
run-name: ${{ github.actor }} ran the workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build; mkdir _site; mv .next/* _site
      - uses: actions/upload-pages-artifact@v3

  github-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4

    permissions:
      id-token: write
      pages: write
