name: JSON
on:
  workflow_dispatch:
    inputs:
      json:
        required: true
        type: string
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ fromJSON(inputs.json) }}
