name: JSON
on:
  workflow_dispatch:
    inputs:
      json:
        required: true
        type: string
jobs:
  job:
    strategy:
      matrix:
        array: ${{ fromJSON(inputs.json) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ matrix.array.name }}
      - run: echo ${{ matrix.array }}
      - run: |
          echo ${{ join(fromJSON(inputs.json).*.name, '\n') }}
