name: Matrix Test
run-name: ${{ github.actor }} ran this workflow

on:
  workflow_dispatch:

jobs:
  build-all:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: matrix.os
    steps:
      - uses: actions/checkout@v4
      - run: echo I am running on ${{ matrix.os }}.
