name: Run On
run-name: ${{ github.actor }} ran this workflow
on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        default: ubuntu-latest
        options:
          - ubuntu-latest
          - windows-latest

jobs:
  hello:
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4
      - run: echo I am running on ${{ inputs.os }}
