name: Tuist
on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: macos-latest
    steps:
        - uses: jdx/mise-action@v2
        - run: mise x tuist -- tuist init --platform ios --template swiftui
        - run: ls -l; tree
