name: Tuist
on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: macos-latest
    steps:
        - uses: jdx/mise-action@v2
        - run: mise x tuist@4.3.4 -- tuist init --platform ios --template default
        - run: mise x tuist@4.3.4 -- tuist generate
        - run: find .
        - uses: actions/upload-artifact@v4
          with:
            path: ./*
